base_url = "https://lbkolev.com"
title = "Lachezar Kolev"
description = "lachezar kolev's blog"
compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]

taxonomies = [
    { name = "tags", feed = true }, # each tag will have its own feed
]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

[extra]
x = "https://x.com/lbkolev"
github = "https://github.com/lbkolev"
email = "lachezarkolevgg@gmail.com"

timeformat = "%B %e, %Y" # e.g. June 14, 2021

katex = true
mermaid = true

[[extra.menu]]
name = "Tags"
url = "tags"

[[extra.menu]]
name = "About"
url = "about"

[extra.footer]
start_year = "2023"
end_year = "∞"

[extra.expressions]
home = "Home"
tags = "Tags"

disqus_discussion = "Discussion and feedback"

p404 = "404: Page not found"
p404_info = "Oops! We can't seem to find the page you are looking for."
p404_back_home_start = "Let's"
p404_back_home_with_link = "head back home"
p404_back_home_end = "."
